name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
      with:
        repository: ChristopherHX/osx-packaging-scripts
        ref: buildfork
    - name: List files
      working-directory: ${{ github.workspace }}
      run: |
        ls -R ${{ github.workspace }}/../.. | awk '
        /:$/&&f{s=$0;f=0}
        /:$/&&!f{sub(/:$/,"");s=$0;f=1;next}
        NF&&f{ print s"/"$0 }'
    - name: Update brew
      run: brew update
    - name: Install brew dependencies
      run: brew install p7zip libzip libuv protobuf
    - name: Install python dependencies
      run: pip3 install jinja2 ds_store
    - name: Download Qt
      working-directory: ${{ github.workspace }}
      run: ${{ github.workspace }}/download_qt.sh
    - name: Build
      working-directory: ${{ github.workspace }}
      run: python3 __main__.py --qt-path qt/*/*/
    - name: Build .dmg
      working-directory: ${{ github.workspace }}
      run: python3 build_dmg.py
    - uses: actions/upload-artifact@master
      with:
        name: DMG Image
        path: ${{ github.workspace }}/output/Minecraft Bedrock Launcher.dmg
