name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
      with:
        repository: ChristopherHX/osx-packaging-scripts
        ref: buildfork
    - name: List files
      working-directory: ${{ github.workspace }}
      run: ls /Applications/Xcode*
    - name: Update brew
      run: brew update
    - name: Install brew dependencies
      run: brew install p7zip libzip libuv protobuf
    - name: Install python dependencies
      run: pip3 install jinja2 ds_store
    - name: Download Qt
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: ./download_qt.sh
    - name: Build
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: |
        curl -L https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.13.sdk.tar.xz --output MacOSX10.13.sdk.tar.xz
        tar -xf MacOSX10.13.sdk.tar.xz
        export MACOSX_DEPLOYMENT_TARGET=10.10
        export SDKROOT=${{ github.workspace }}/../osx-packaging-scripts/MacOSX10.13.sdk
        python3 __main__.py --qt-path qt/*/*/
        
    - name: Build .dmg
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: python3 build_dmg.py
    - uses: actions/upload-artifact@master
      with:
        name: DMG Image
        path: ${{ github.workspace }}/../osx-packaging-scripts/output/Minecraft Bedrock Launcher.dmg
