name: CI
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      with:
        repository: ChristopherHX/osx-packaging-scripts
        ref: buildfork
    - uses: actions/checkout@v1
      with:
        repository: ChristopherHX/MacOSX10.14.sdk
        ref: 5d1c9b28f01ef0b01225f92670ee587b430efa8e
        token: ${{ secrets.MacOSX1013sdk }}
    - name: Apply custom patch and Update brew
      working-directory: "/usr/local/Homebrew"
      run: |
        brew update
        git remote add fork https://github.com/ChristopherHX/brew.git
        git fetch fork
        git config --global user.email "CI@local"
        git config --global user.name "CI Bot"
        git merge fork/master
    - name: Install brew dependencies
      run: |
        export HOMEBREW_MACOSX_DEPLOYMENT_TARGET=10.13.0
        export HOMEBREW_SDKROOT=${{ github.workspace }}/../MacOSX10.14.sdk
        brew install p7zip libzip libuv protobuf
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - uses: actions/setup-python@v1
      with:
        python-version: '2.x' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified  
    - name: Show python versions
      run: python --version && python2 --version && python3 --version
    - name: Install python dependencies
      run: python3 -m pip install --upgrade pip && pip3 install jinja2 ds_store
    - name: Download Qt
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: ./download_qt.sh
    - name: Build
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.12
        export SDKROOT=${{ github.workspace }}/../MacOSX10.14.sdk
        python3 __main__.py --qt-path qt/*/*/ --update-url https://github.com/ChristopherHX/mcpelauncher-manifest/releases/download/Snapshot/version.osx --build-id ${GITHUB_RUN_NUMBER}
    - name: Build .dmg
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: python3 build_dmg.py
    - name: Upload Latest
      run: mkdir -p dist && mv ""${{ github.workspace }}/../osx-packaging-scripts/output/Minecraft Bedrock Launcher.dmg" dist/Minecraft_Bedrock_Launcher.dmg && echo build_id=${GITHUB_RUN_NUMBER}$'\n'download_url=https://github.com/ChristopherHX/mcpelauncher-manifest/releases/download/Snapshot/Minecraft_Bedrock_Launcher.dmg > dist/version.osx && curl -L https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_darwin_amd64.zip --output ghr.zip && unzip ghr.zip && ./ghr*/ghr -t ${{ secrets.MacOSX1013sdk }} -u ChristopherHX -r mcpelauncher-manifest -recreate -b "[First read my README](https://github.com/ChristopherHX/mcpelauncher-manifest) for current Features, known Issues / Bugs, Sourcecode or Linux Releases"$'\n'"**Only MacOs (10.12 brew stopped supporting it), 10.13 and 10.14 are supported**"$'\n'"**reduced gpu performance, some textures are white** Patched [ANGLE - Almost Native Graphics Layer Engine](https://github.com/minecraft-linux/angle)" Snapshot dist/