name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
      with:
        repository: ChristopherHX/osx-packaging-scripts
        ref: buildfork
    - uses: actions/checkout@v1
      with:
        repository: ChristopherHX/MacOSX10.13.sdk
        ref: d4e62526638c82e8e62fef0de0ad767a1f798671
        token: ${{ secrets.MacOSX1013sdk }}
    - name: Apply custom patch and Update brew
      working-directory: "/usr/local/Homebrew"
      run: |
        brew update
        git remote add fork https://github.com/ChristopherHX/brew.git
        git fetch fork
        git config --global user.email "CI@local"
        git config --global user.name "CI Bot"
        git merge fork/master
    - name: Install brew dependencies
      run: |
        export HOMEBREW_MACOSX_DEPLOYMENT_TARGET=10.12.0
        export HOMEBREW_SDKROOT=${{ github.workspace }}/../MacOSX10.13.sdk
        brew install p7zip libzip libuv protobuf || :
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Find Python
      run: 'python2 --version && ls -l /Users/runner/hostedtoolcache/Python/2.*/* || :'
    - name: Install python dependencies
      run: pip install jinja2 ds_store
    - name: Download Qt
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: ./download_qt.sh
    - name: Build
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.12
        export SDKROOT=${{ github.workspace }}/../MacOSX10.13.sdk
        python __main__.py --qt-path qt/*/*/
        
    - name: Build .dmg
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: python3 build_dmg.py
    - uses: actions/upload-artifact@master
      with:
        name: DMG(sdk10.13)
        path: ${{ github.workspace }}/../osx-packaging-scripts/output/Minecraft Bedrock Launcher.dmg
  buildSDK_10_14:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
      with:
        repository: ChristopherHX/osx-packaging-scripts
        ref: buildfork
    - uses: actions/checkout@v1
      with:
        repository: ChristopherHX/MacOSX10.14.sdk
        ref: 5d1c9b28f01ef0b01225f92670ee587b430efa8e
        token: ${{ secrets.MacOSX1013sdk }}
    - name: Apply custom patch and Update brew
      working-directory: "/usr/local/Homebrew"
      run: |
        brew update
        git remote add fork https://github.com/ChristopherHX/brew.git
        git fetch fork
        git config --global user.email "CI@local"
        git config --global user.name "CI Bot"
        git merge fork/master
    - name: Install brew dependencies
      run: |
        export HOMEBREW_MACOSX_DEPLOYMENT_TARGET=10.12.0
        export HOMEBREW_SDKROOT=${{ github.workspace }}/../MacOSX10.14.sdk
        brew install p7zip libzip libuv protobuf || :
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Install python dependencies
      run: pip install jinja2 ds_store
    - name: Download Qt
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: ./download_qt.sh
    - name: Build
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.12
        export SDKROOT=${{ github.workspace }}/../MacOSX10.14.sdk
        python __main__.py --qt-path qt/*/*/
        
    - name: Build .dmg
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: python3 build_dmg.py
    - uses: actions/upload-artifact@master
      with:
        name: DMG(sdk10.14)
        path: ${{ github.workspace }}/../osx-packaging-scripts/output/Minecraft Bedrock Launcher.dmg
  uploadlatest:
    runs-on: ubuntu-latest
    needs: [build, buildSDK_10_14]
    steps:
    - name: Download sdk 10.13 Release
      uses: actions/download-artifact@v1
      with:
        name: DMG(sdk10.13)
    - name: Download sdk 10.14 Release
      uses: actions/download-artifact@v1
      with:
        name: DMG(sdk10.14)
    - name: Move to artifacts
      run: mkdir -p artifacts && mv DMG\(sdk10.13\)/*.dmg ./artifacts/Minecraft_Bedrock_Launcher_FORK_sdk10.13.dmg &&  mv DMG\(sdk10.14\)/*.dmg ./artifacts/Minecraft_Bedrock_Launcher_FORK_sdk10.14.dmg
    - name: Upload Latest
      run: curl -L https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz --output ghr.tar.gz && tar -xf ghr.tar.gz && ./ghr*/ghr -t ${{ secrets.MacOSX1013sdk }} -u ChristopherHX -r ChristopherHX/mcpelauncher-manifest -delete -b "[First read my README](https://github.com/ChristopherHX/mcpelauncher-manifest) for current Features, known Issues / Bugs, Sourcecode or Linux Releases"$'\n'"**Only MacOs 10.12, 10.13 and 10.14 are supported**" MacOsLatest artifacts
