name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
      with:
        repository: ChristopherHX/osx-packaging-scripts
        ref: buildfork
    - uses: actions/checkout@v1
      with:
        repository: ChristopherHX/MacOSX10.13.sdk
        ref: d4e62526638c82e8e62fef0de0ad767a1f798671
        token: ${{ secrets.MacOSX1013sdk }}
    - name: List files
      working-directory: ${{ github.workspace }}
      run: ls /Applications/Xcode*
    - name: Update brew
      run: brew update
    - name: Install brew dependencies
      run: brew install p7zip libpng libzip libuv protobuf
    - name: Install python dependencies
      run: pip3 install jinja2 ds_store
    - name: Download Qt
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: ./download_qt.sh
    - name: Build
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.12
        export SDKROOT=${{ github.workspace }}/../MacOSX10.13.sdk
        python3 __main__.py --qt-path qt/*/*/
        
    - name: Build .dmg
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: python3 build_dmg.py
    - uses: actions/upload-artifact@master
      with:
        name: DMG(sdk10.13)
        path: ${{ github.workspace }}/../osx-packaging-scripts/output/Minecraft Bedrock Launcher.dmg
  buildSDK_10_14:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
      with:
        repository: ChristopherHX/osx-packaging-scripts
        ref: buildfork
    - uses: actions/checkout@v1
      with:
        repository: ChristopherHX/MacOSX10.14.sdk
        ref: 5d1c9b28f01ef0b01225f92670ee587b430efa8e
        token: ${{ secrets.MacOSX1013sdk }}
    - name: List files
      working-directory: ${{ github.workspace }}
      run: ls /Applications/Xcode*
    - name: Update brew
      run: brew update
    - name: Install brew dependencies
      run: brew install p7zip libpng libzip libuv protobuf
    - name: Install python dependencies
      run: pip3 install jinja2 ds_store
    - name: Download Qt
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: ./download_qt.sh
    - name: Build
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.12
        export SDKROOT=${{ github.workspace }}/../MacOSX10.14.sdk
        python3 __main__.py --qt-path qt/*/*/
        
    - name: Build .dmg
      working-directory: ${{ github.workspace }}/../osx-packaging-scripts
      run: python3 build_dmg.py
    - uses: actions/upload-artifact@master
      with:
        name: DMG(sdk10.14)
        path: ${{ github.workspace }}/../osx-packaging-scripts/output/Minecraft Bedrock Launcher.dmg
    - name: Upload Latest
      run: curl -L https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_darwin_amd64.zip --output ghr.zip && unzip ghr.zip && ./ghr*/ghr -t ${{ secrets.MacOSX1013sdk }} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete MacOsLatest "${{ github.workspace }}/../osx-packaging-scripts/output/Minecraft Bedrock Launcher.dmg"
